### ISSUE TITLE
Enable crow sounds

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/BeforeVancouver#2]
Script for crow sounds seems not to be working

**Comment by tedbarnett** [comment]
I tried adding sounds as you suggested, but got a console error: 
NullReferenceException: Object reference not set to an instance of an object
FlockChildSound.PlayRandomSound () (at Assets/Bird Flocks/Scripts/FlockChildSound.cs:39)


![capture](https://user-images.githubusercontent.com/694013/42908677-72cf2740-8a96-11e8-9ca2-5860883a2986.JPG)

**Comment by ericboise** [comment]
I looked at the asset and it seems that FlockChild.cs needs to be on the prefab for the individual crow.  This might not work for performance reasons.  I'm going to keep messing with it but working now.

**Comment by ericboise** [comment]
I disabled the audio on the crow prefab and just set one audio clip to play on the Crow Flock game object.  This is better for performance but will need a better audio file.
