### ISSUE TITLE
Enable Oculus GO version

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/BeforeVancouver#5]
May need an alternative terrain (without trees, etc.). 

Use VRTK?

**Comment by tedbarnett** [comment]
See https://developer.oculus.com/blog/everything-you-need-to-know-to-develop-for-oculus-go/

**Comment by ericboise** [comment]
Will need Go hardware to get this working.  Project has latest Oculus SDK's so should be too tough

**Comment by tedbarnett** [comment]
I got it working, and re-assigned some of the buttons (using trigger and A button on Oculus GO controller).  Can't test on Rift currently (while  in Vancouver), but we're only using the GOs these 2 weeks so not an issue...
