### ISSUE TITLE
Enable Night/Day cycling (as in MillValley1920)

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/BeforeVancouver#7]
First priority: keyboard "N"
2nd priority: Oculus Controller trackpad button (as in MillValley1920)

**Comment by tedbarnett** [comment]
We have two skybox materials to use: Sky_11 (daytime, default), and Sky50 (nighttime)

**Comment by ericboise** [comment]
Day/night cycle set with 'N' key press. Still wip for controller

**Comment by ericboise** [comment]
Oculus Touch Right Controller B button toggles Day/Night

**Comment by tedbarnett** [comment]
Works!
