### ISSUE TITLE
Enable VRTK (VR/PC controllers)

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/BeforeVancouver#8]
If app is launched on PC with Oculus present, run Oculus Rift VR (touch controller and callouts)
If not available, launch as desktop app (WASD controls)

**Comment by ericboise** [comment]
So VRTK is not ready for new Oculus SDK's.  I put into the project and it's pretty broken (plus a Unity 2018.2 VR bug that needs fixed)  I recommend a simple movement/input control with the OVRInputs.

**Comment by ericboise** [comment]
Used Oculus Examples for teleport with Oculus Touch Right thumbstick, Press direction and angle of thumbstick to select teleport location. (lots of other options) Should work fine if HMD is not present. WASD and/or Xbox Controller to move and Y/N to toggle year and day/night
No VRTK, no callouts yet
