### ISSUE TITLE
Enable Time Change ("Y")

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/BeforeVancouver#9]
Only 2 periods: 1800 and 2018.  Default is 1800.

**Comment by ericboise** [comment]
Example time period holders game objects and toggling with Y enables/disables, still wip

**Comment by ericboise** [comment]
done, Object holders are a child of VancouverScene gameobject

**Comment by ericboise** [comment]
A button on Oculus Touch Right Controller

**Comment by tedbarnett** [comment]
Works great!
